folio-org/mod-password-validator

NEWS.md, README.md, pom.xml, ramls/defaultRules/defaultRules.json, src/main/resources/templates/db_scripts/populate-rules.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/PasswordResourceTest.java, src/test/java/org/folio/services/validator/engine/ValidateDefaultRulesUnitTest.java
* Created initial ruleset for a tenant
* Added validation tests for password
=> MODLOGIN-52 Initial ruleset for a tenant, MODLOGIN-57 Create password validation rules (RegEx)

pom.xml
Reference: https://github.com/mojohaus/aspectj-maven-plugin/issues/18
=> MODLOGIN-79: Update aspectj to make it work in eclipse.

ramls/password-validator.raml, src/main/java/org/folio/rest/impl/ValidateResourceImpl.java, src/test/java/org/folio/rest/impl/PasswordResourceTest.java
=> fix password validate endpoint

descriptors/ModuleDescriptor-template.json, ramls/defaultRules/defaultRules.json, src/main/resources/templates/db_scripts/populate-rules.sql
=> MODLOGIN-33: Prevent Local Password Re-Use

NEWS.md, README.md
=> FOLIO-722 initial repo setup

src/main/java/org/folio/rest/impl/TenantRulesImpl.java, src/test/java/org/folio/rest/impl/PasswordResourceTest.java, src/test/java/org/folio/rest/impl/ValidatorRegistryTest.java
**Approach**
Add additional tests to cover invalid or unsuccessful cases
**Link**
[MODPWD-16](https://issues.folio.org/browse/MODPWD-16)
=> MODPWD-16 Increase test coverage for mod-password-validator

pom.xml
=> Fix security vulnerabilities reported in jackson-databind

ramls/password.json, src/main/java/org/folio/rest/impl/PasswordImpl.java, src/main/java/org/folio/services/validator/engine/ValidationEngineService.java, src/main/java/org/folio/services/validator/engine/ValidationEngineServiceImpl.java, src/main/java/org/folio/services/validator/util/ValidatorHelper.java, src/test/java/org/folio/rest/impl/PasswordResourceTest.java, src/test/java/org/folio/services/validator/engine/ProgrammaticRulesProcessingTest.java, src/test/java/org/folio/services/validator/engine/RegExpRulesProcessingTest.java, src/test/java/org/folio/services/validator/engine/ValidateDefaultRulesUnitTest.java
**Purpose**
Update `mod-password-validator` contract to implement a user password reset by link
Resolves: [MODPWD-20](https://issues.folio.org/browse/MODPWD-20)
=> MODPWD-20 Change user password validation implementation [Reset passwords: user can reset password by link]

src/test/java/org/folio/rest/impl/ValidatorRegistryTest.java
There is no query and no sortBy, the order of the returned rules depends on the database version and state.
=> Ignore the order the rules are returned.

pom.xml, src/main/java/org/folio/services/validator/engine/ValidationEngineServiceImpl.java, src/main/java/org/folio/services/validator/registry/ValidatorRegistryServiceImpl.java
- Update to RMB v30.0.2
- Update vertx to 3.9.1
- Do all related changes according to RMB upgrading notes
Resolves: [MODPWD-37](https://issues.folio.org/browse/MODPWD-37)
=> MODPWD-37 update RMB and vetx versions

pom.xml
=> MODPWD-39 mod-password-validator: Update to RMB v31.x

descriptors/DeploymentDescriptor-template.json, descriptors/ModuleDescriptor-template.json
Fix placeholders for artifact naming/version in descriptors
=> Fix placeholders for artifact naming/version in descriptors

PERSONAL_DATA_DISCLOSURE.md
Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
* add PERSONAL_DATA_DISCLOSURE.md file
=> MODPWD-54 Add personal data disclosure form

pom.xml
Upgrade to stable version of folio-spring-base v1.0.1 instead of snapshot
=> Upgrade to folio-spring-base v1.0.1

Jenkinsfile, descriptors/ModuleDescriptor-template.json, pom.xml, run-env.sh, src/main/resources/application.yaml
Add admin health-check endpoint with Url: /admin/health
Utilize Sprint boot actuator health check. Replace standard path to /admin/health via app property. Enable health check in Jenkins settings
=> MODPWD-59 Add admin health-check endpoint

lombok.config
=> Add Lombok configuration

README.md
The README.md is out of date regarding the validation rules.
Update the documentation in README.md regarding the validation rules.
Update the documentation in README.md regarding the validation rules.
When changing the code update the README.md.
=> MODPWD-71: Update rule documentation in README.md

descriptors/ModuleDescriptor-template.json
Fix problem when User can not reset his password
Fix permissions
=> MODPWD-77 Fix permissions

descriptors/ModuleDescriptor-template.json
Make /tenant/rules endpoint publicly accessible
Remove the permission to make endpoint publicly accessible
=> MODPWD-83 Make /tenant/rules endpoint publicly accessible

NEWS.md, pom.xml
Release 2.1.1
Fix log4j2
https://issues.folio.org/browse/MODPWD-86
=> Release 2.1.1

src/main/resources/db/changelog/changes/v2.1.0/cleanup.xml
=> MODPWD-94 Fix cleanup script migration

NEWS.md, pom.xml
- Update folio-spring-base to v4.1.0
- Update dependencies
=> MODPWD-98 Update folio-spring-base to v4.1.0

NEWS.md, pom.xml
Update folio-spring-base to v5.0.0
- Update parent and dependencies
[MODPWD-103](https://issues.folio.org/browse/MODPWD-103)
=> MODPWD-103 Update folio-spring-base to v5.0.0

NEWS.md, doc/RELEASES.md, pom.xml
Release v2.5
[MODPWD-104](https://issues.folio.org/browse/MODPWD-104)
=> Tmp release v2.5

PULL_REQUEST_TEMPLATE.md, src/main/resources/application.yaml
_Logging should be improved for more productive troubleshooting._
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Enable the /loggers endpoint in our application.properties file by adding the following lines:
- management.endpoints.web.exposure.include=loggers
- management.endpoint.loggers.enabled=true
- The version of the folio-spring-base should be updated (see [FOLSPRINGB-45](https://issues.folio.org/browse/FOLSPRINGB-45))
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODPWD-108
=> MODPWD-108 - Logging improvement - Configuration

src/test/java/org/folio/pv/api/PasswordValidatorControllerIT.java, src/test/java/org/folio/pv/api/ValidationRulesControllerIT.java
Fix coverage in master branch
Rename integration tests to end with "IT"
=> Coverage fix

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> MODPWD-117 Poppy release

pom.xml, src/main/java/org/folio/pv/domain/entity/PasswordValidationRule.java
Upgrade the spring version for Q release.
=> MODPWD-119 - Upgrade to spring version for Q release.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> [MODPWD-121]-Q Release

NEWS.md, pom.xml
=> T0 release 3.2.1

NEWS.md, pom.xml
=> Post release 3.2.1

pom.xml
The purpose of the PR is to implement [MODPWD-125](https://folio-org.atlassian.net/browse/MODPWD-125)
=> MODPWD-125 update folio spring base version for ramson

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Ramsons Release

checkstyle/checkstyle.xml, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/pv/controller/ErrorHandlingController.java, src/main/java/org/folio/pv/controller/PasswordValidatorController.java, src/main/java/org/folio/pv/domain/dto/UserData.java, src/main/java/org/folio/pv/service/CacheEvictionService.java, src/main/java/org/folio/pv/service/PasswordValidatorService.java, src/main/java/org/folio/pv/service/PasswordValidatorServiceImpl.java, src/main/java/org/folio/pv/service/ValidationRuleService.java, src/main/java/org/folio/pv/service/ValidationRuleServiceImpl.java, src/main/java/org/folio/pv/service/exception/NoRulesMatchedException.java, src/main/resources/application.yaml, src/main/resources/swagger.api/password-validator.yaml, src/main/resources/swagger.api/schemas/password_check.json, src/test/java/org/folio/pv/api/PasswordValidatorControllerIT.java, src/test/java/org/folio/pv/service/PasswordValidatorServiceImplTest.java, src/test/java/org/folio/pv/service/ValidationRuleServiceImplTest.java, src/test/java/org/folio/pv/testutils/ApiTestUtils.java
[MODPWD-130](https://folio-org.atlassian.net/browse/MODPWD-130): Add new endpoint to check password
- added new endpoint /password/check to check password on the pre registration flow
- added unit and integration tests
=> MODPWD-130: Add new endpoint to check password

src/main/java/org/folio/pv/service/PasswordValidatorServiceImpl.java, src/test/java/org/folio/pv/api/PasswordValidatorControllerIT.java
[MODPWD-131](https://folio-org.atlassian.net/browse/MODPWD-131): Update /password/check filtering for validation rules
- remove enabled rules filter
=> MODPWD-131: Update password check endpoint rules filter

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/test/java/org/folio/pv/api/BaseApiTest.java, src/test/java/org/folio/pv/api/PasswordValidatorControllerIT.java, src/test/java/org/folio/pv/api/ValidationRulesControllerIT.java, src/test/java/org/folio/pv/client/HashedPasswordUsageCollectionConverterTest.java, src/test/java/org/folio/pv/service/ValidationRuleServiceImplTest.java, src/test/java/org/folio/pv/service/validator/PwnedPasswordValidatorTest.java, src/test/java/org/folio/pv/service/validator/RegExpValidatorTest.java, src/test/java/org/folio/pv/service/validator/ValidatorRegistryImplTest.java
[MODPWD-136](https://folio-org.atlassian.net/browse/MODPWD-136)
=> MODPWD-136 Sunflower R1 2025-03-14

.github/dependabot.yml, PULL_REQUEST_TEMPLATE.md
- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- add `dependabot.yml` config file
- update `PULL_REQUEST_TEMPLATE.md` file
[MODPWD-138](https://folio-org.atlassian.net/browse/MODPWD-138)
=> MODPWD-138: Add config file for dependabot and template for pull request
